command: ["node", "dist/index.js", "--transport", "http", "--port", "8000", "--host", "0.0.0.0"]
env:
  - name: BRAVE_API_KEY
    valueFrom: BRAVE-API-KEY
  - name: BRAVE_MCP_TRANSPORT  
    value: "http"
  - name: BRAVE_MCP_PORT
    value: "8000"
  - name: BRAVE_MCP_HOST
    value: "0.0.0.0"
