command: ["node", "dist/index.js", "--transport", "http", "--host", "0.0.0.0"]
env:
  - name: BRAVE_API_KEY
    # valueFrom: "brave-api-key"
    value: "BSATpVvbObo2V8IVewHsLo9xGE1i8Bf"
  - name: BRAVE_MCP_TRANSPORT  
    value: "http"
  - name: BRAVE_MCP_PORT
    valueFrom: PORT
  - name: BRAVE_MCP_HOST
    value: "0.0.0.0"
