command: ["node", "dist/index.js", "--transport", "http", "--port", "8080", "--host", "0.0.0.0"]
env:
  - name: BRAVE_API_KEY
    valueFrom: "secret"
    key: "brave-api-key"
  - name: BRAVE_MCP_TRANSPORT  
    value: "http"
  - name: BRAVE_MCP_PORT
    value: "8080"
  - name: BRAVE_MCP_HOST
    value: "0.0.0.0"
